- name: Remove packages included in basic-desktop software selection
  dnf:
    name:
      - awesome
      - cronie
      - fprintd
      - i3
      - initial-setup-gui
      - openbox
      - pcsc-lite
      - qtile
      - ratpoison
      - virtualbox-guest-additions
      - xmonad-core
    state: absent

- name: Ensure NetworkManager-wifi exists
  dnf: name=NetworkManager-wifi

- name: Autoremove leaf packages
  dnf: autoremove=true

- name: Replace pipewire-pulseaudio with pulseaudio
  dnf: name=pulseaudio allowerasing=yes
  when: releasever | int >= 34
